// GENERATED by scripts/generate-services.js from public/eldava-app.js.
// Do not edit by hand - change SERVICES in eldava-app.js and re-run the script.
//
// Prices are in PENCE. The browser is never trusted for a price: every booking
// looks the service up here by name and charges this figure.

export type Service = {
  name: string;
  cat: string;
  desc: string;
  priceMinor: number;
  durationLabel: string;
  durationMin: number;
};

export const CATEGORIES: Record<string, string> = {
  "all": "All",
  "mind": "Mental Health and Neurodevelopmental",
  "women": "Women's Health and Maternity",
  "child": "Children and SEND",
  "body": "Adult Specialties",
  "testing": "Objective Testing",
  "postdx": "Post-Diagnostic Support",
  "premium": "Premium Packages",
  "legal": "Medico-Legal",
  "dementia": "Dementia Care",
  "mens": "Men's Health",
  "skin": "Skin and Dermatology",
  "hearing": "Hearing and Eye Care",
  "founding": "Founding 500 Vouchers"
};

/// Category of the Founding 500 prepaid vouchers - bought now, redeemed later,
/// so they bypass slot selection and count toward the 500 cap.
export const FOUNDING_CAT = 'founding';
export const FOUNDING_CAP = 500;

export const SERVICES: Service[] = [
  { name: "Child Autism Assessment", cat: "mind", desc: "Full diagnostic assessment for children", priceMinor: 91500, durationLabel: "90 min", durationMin: 90 },
  { name: "Child ADHD Assessment", cat: "mind", desc: "Full diagnostic assessment for children", priceMinor: 80000, durationLabel: "75 min", durationMin: 75 },
  { name: "Combined Child Assessment", cat: "mind", desc: "ADHD and autism, children", priceMinor: 137500, durationLabel: "120 min", durationMin: 120 },
  { name: "Adult ADHD Assessment", cat: "mind", desc: "Diagnostic assessment for adults", priceMinor: 68500, durationLabel: "60 min", durationMin: 60 },
  { name: "Adult Autism Assessment", cat: "mind", desc: "Diagnostic assessment for adults", priceMinor: 80000, durationLabel: "75 min", durationMin: 75 },
  { name: "Adult Combined Assessment", cat: "mind", desc: "ADHD and autism, adults", priceMinor: 114500, durationLabel: "90 min", durationMin: 90 },
  { name: "Psychiatry Consultation", cat: "mind", desc: "Depression, anxiety, OCD", priceMinor: 17500, durationLabel: "45 min", durationMin: 45 },
  { name: "Trauma and PTSD", cat: "mind", desc: "EMDR and trauma focused CBT", priceMinor: 14000, durationLabel: "50 min", durationMin: 50 },
  { name: "Eating Disorders", cat: "mind", desc: "Assessment and therapy", priceMinor: 17500, durationLabel: "50 min", durationMin: 50 },
  { name: "Antenatal Consultation", cat: "women", desc: "Pregnancy advice", priceMinor: 3500, durationLabel: "30 min", durationMin: 30 },
  { name: "Postnatal Consultation", cat: "women", desc: "Post birth recovery advice", priceMinor: 7000, durationLabel: "30 min", durationMin: 30 },
  { name: "Lactation Consultation", cat: "women", desc: "Breastfeeding support", priceMinor: 11000, durationLabel: "45 min", durationMin: 45 },
  { name: "Gynaecology Advice", cat: "women", desc: "Menstrual disorders, menopause", priceMinor: 11500, durationLabel: "30 min", durationMin: 30 },
  { name: "Fertility Advice", cat: "women", desc: "Pre conception, hormone tests", priceMinor: 17500, durationLabel: "45 min", durationMin: 45 },
  { name: "Menopause Advice", cat: "women", desc: "HRT, symptom management", priceMinor: 11500, durationLabel: "30 min", durationMin: 30 },
  { name: "Speech and Language Therapy", cat: "child", desc: "Per session", priceMinor: 7000, durationLabel: "45 min", durationMin: 45 },
  { name: "Occupational Therapy", cat: "child", desc: "Per session", priceMinor: 8000, durationLabel: "45 min", durationMin: 45 },
  { name: "Educational Psychologist Assessment (EHCP)", cat: "child", desc: "Diagnostic assessment covering dyslexia and other specific learning difficulties, written up as an EHCP-ready report for schools and local authorities", priceMinor: 103500, durationLabel: "120 min", durationMin: 120 },
  { name: "Paediatric Physiotherapy", cat: "child", desc: "Per session", priceMinor: 8500, durationLabel: "45 min", durationMin: 45 },
  { name: "Dermatology Advice", cat: "body", desc: "Remote photo diagnosis", priceMinor: 6000, durationLabel: "20 min", durationMin: 20 },
  { name: "Cardiology Advice", cat: "body", desc: "Risk assessment, lifestyle", priceMinor: 6000, durationLabel: "30 min", durationMin: 30 },
  { name: "ENT Triage", cat: "body", desc: "Hearing, tinnitus advice", priceMinor: 6000, durationLabel: "20 min", durationMin: 20 },
  { name: "Ophthalmology Advice", cat: "body", desc: "Cataract, glaucoma advice", priceMinor: 6000, durationLabel: "20 min", durationMin: 20 },
  { name: "Neurology Advice", cat: "body", desc: "Headache, migraine advice", priceMinor: 6000, durationLabel: "30 min", durationMin: 30 },
  { name: "Urology Advice", cat: "body", desc: "Prostate, UTI advice", priceMinor: 6000, durationLabel: "20 min", durationMin: 20 },
  { name: "Dyslexia and SpLD Assessment (DSA)", cat: "body", desc: "Adult diagnostic assessment and report for university Disabled Students’ Allowance applications or workplace needs assessments", priceMinor: 74800, durationLabel: "150 min", durationMin: 150 },
  { name: "QbTest Objective ADHD Testing", cat: "testing", desc: "Computer based attention and activity test, added to any ADHD assessment", priceMinor: 15000, durationLabel: "25 min", durationMin: 25 },
  { name: "Pharmacogenomic Medication Test", cat: "testing", desc: "Genetic test to help guide medication choice and dosing", priceMinor: 45000, durationLabel: "Sample only", durationMin: 60 },
  { name: "SensoDetect Neuro-Auditory Screening", cat: "testing", desc: "Objective auditory screening to support diagnosis", priceMinor: 7500, durationLabel: "20 min", durationMin: 20 },
  { name: "Enhanced Assessment Bundle", cat: "testing", desc: "Full assessment plus QbTest, PGx and SensoDetect", priceMinor: 145000, durationLabel: "Multi-part", durationMin: 60 },
  { name: "Cognitive Function Test", cat: "testing", desc: "Structured memory and focus assessment", priceMinor: 19500, durationLabel: "40 min", durationMin: 40 },
  { name: "Fertility Hormone Panel", cat: "testing", desc: "AMH, FSH, oestradiol and progesterone", priceMinor: 22500, durationLabel: "Sample only", durationMin: 60 },
  { name: "Menopause Hormone Panel", cat: "testing", desc: "FSH, oestradiol and testosterone", priceMinor: 15000, durationLabel: "Sample only", durationMin: 60 },
  { name: "ADHD Coaching Programme", cat: "postdx", desc: "12 one to one coaching sessions", priceMinor: 85000, durationLabel: "12 sessions", durationMin: 60 },
  { name: "CBT for Anxiety", cat: "postdx", desc: "12 one to one cognitive behavioural therapy sessions", priceMinor: 115000, durationLabel: "12 sessions", durationMin: 60 },
  { name: "Parenting Support Programme", cat: "postdx", desc: "Structured support for parents of a newly diagnosed child", priceMinor: 47500, durationLabel: "6 weeks", durationMin: 60 },
  { name: "Nutrition Consultation", cat: "postdx", desc: "Dietitian led advice, including for ADHD and autism related eating patterns", priceMinor: 9500, durationLabel: "45 min", durationMin: 45 },
  { name: "Medication Titration and Monitoring", cat: "postdx", desc: "12 week medication plan with review appointments", priceMinor: 95000, durationLabel: "12 weeks", durationMin: 60 },
  { name: "Annual Care Plan", cat: "postdx", desc: "Annual review, 4 coaching sessions and prescription support", priceMinor: 65000, durationLabel: "12 months", durationMin: 60 },
  { name: "Complete Pathway Package", cat: "premium", desc: "Assessment, coaching, medication review and objective testing", priceMinor: 320000, durationLabel: "Multi-session", durationMin: 60 },
  { name: "Priority Access Package", cat: "premium", desc: "Appointment within 48 hours, evening and weekend slots", priceMinor: 180000, durationLabel: "60 min", durationMin: 60 },
  { name: "Family Assessment Package", cat: "premium", desc: "Two adult and two child assessments plus family coaching", priceMinor: 360000, durationLabel: "Multi-session", durationMin: 60 },
  { name: "Medico-Legal Expert Report", cat: "legal", desc: "Court ready psychiatric or psychological expert witness report, clinician available for cross examination", priceMinor: 280000, durationLabel: "From 3 hours", durationMin: 60 },
  { name: "Dementia Memory Assessment", cat: "dementia", desc: "Full diagnostic memory assessment with structured cognitive testing, medical history, medication review and a collateral history from a family member where possible, plus a written report for your GP or memory clinic", priceMinor: 89500, durationLabel: "90 min", durationMin: 90 },
  { name: "Mild Cognitive Impairment Pathway", cat: "dementia", desc: "Structured assessment and a personalised monitoring plan, with a 6 month review appointment to track change over time", priceMinor: 49500, durationLabel: "60 min plus 6 month review", durationMin: 60 },
  { name: "Post-Diagnostic Dementia Support Programme", cat: "dementia", desc: "Six clinician-led sessions for the person diagnosed and their family, covering what the diagnosis means, planning ahead, communication strategies and accessing support", priceMinor: 57500, durationLabel: "6 weekly sessions", durationMin: 60 },
  { name: "Dementia Carer Support Programme", cat: "dementia", desc: "Six clinician-led sessions for a family carer, covering behaviour changes, managing your own health and knowing when and how to ask for help", priceMinor: 47500, durationLabel: "6 weekly sessions", durationMin: 60 },
  { name: "Mental Capacity Assessment", cat: "dementia", desc: "Clinician conducted and signed assessment for Lasting Power of Attorney, deputyship applications (COP3), wills and property or financial decisions, with a written report issued to your legal adviser", priceMinor: 69500, durationLabel: "90 min", durationMin: 90 },
  { name: "Best Interests Assessment", cat: "dementia", desc: "Section 4 Mental Capacity Act assessment for care and treatment decisions, including care plan reviews and discharge planning", priceMinor: 75000, durationLabel: "90 min", durationMin: 90 },
  { name: "Dementia Family Pathway", cat: "premium", desc: "A memory assessment, the carer support programme, a capacity review and priority access to our clinicians when things change, across the first year after concerns begin", priceMinor: 295000, durationLabel: "Multi-session, 12 months", durationMin: 60 },
  { name: "Dementia Medico-Legal Report", cat: "legal", desc: "Court ready expert report on capacity, testamentary capacity or litigation capacity, prepared by an experienced clinician available for cross examination", priceMinor: 240000, durationLabel: "From 3 hours", durationMin: 60 },
  { name: "Men's Health MOT", cat: "mens", desc: "Full review of cardiovascular risk, hormones, weight, sleep and lifestyle, with a written summary and a plan for the next 12 months", priceMinor: 15000, durationLabel: "45 min", durationMin: 45 },
  { name: "Male Hormone Panel", cat: "mens", desc: "Testosterone and related markers by home sample kit, reviewed in a consultation with a clinician", priceMinor: 19500, durationLabel: "Sample only", durationMin: 60 },
  { name: "Erectile Dysfunction Consultation", cat: "mens", desc: "Private consultation covering causes, lifestyle factors and treatment options, including medication where appropriate", priceMinor: 9500, durationLabel: "30 min", durationMin: 30 },
  { name: "Prostate Health Review", cat: "mens", desc: "Advice on urinary symptoms, PSA testing decisions and when to be seen in person", priceMinor: 8500, durationLabel: "30 min", durationMin: 30 },
  { name: "Male Fertility Assessment", cat: "mens", desc: "Semen analysis results reviewed with a clinician, plus hormone testing where indicated, lifestyle guidance and a referral pathway to specialist treatment if needed", priceMinor: 18500, durationLabel: "45 min", durationMin: 45 },
  { name: "Endometriosis Specialist Advice", cat: "women", desc: "Consultation with a clinician experienced in endometriosis and pelvic pain, covering your history, which tests to request and how to get referred", priceMinor: 16500, durationLabel: "45 min", durationMin: 45 },
  { name: "Endometriosis Pathway", cat: "women", desc: "Specialist advice, a hormone panel by home sample, and a written referral letter and summary for your GP or gynaecologist", priceMinor: 49500, durationLabel: "Multi-part", durationMin: 60 },
  { name: "PCOS Assessment and Advice", cat: "women", desc: "Symptoms reviewed, testing explained and a management plan covering hormones, weight, skin and fertility implications, with a written summary for your GP", priceMinor: 16500, durationLabel: "45 min", durationMin: 45 },
  { name: "Rapid Skin Assessment", cat: "skin", desc: "Secure photo and video review by a clinician, with written assessment and treatment guidance, or a clear answer on whether you need an in person examination", priceMinor: 9500, durationLabel: "20 min", durationMin: 20 },
  { name: "Skin Fast Track Package", cat: "skin", desc: "Assessment plus a structured private referral pathway for lesions that need urgent in person review. We do not provide a skin cancer diagnosis by telehealth; any lesion of concern is escalated for in person review.", priceMinor: 45000, durationLabel: "Multi-part", durationMin: 60 },
  { name: "Hearing Assessment", cat: "hearing", desc: "Structured consultation on your hearing concerns, history and function, with objective screening and guidance on whether hearing aids would help", priceMinor: 9500, durationLabel: "30 min", durationMin: 30 },
  { name: "Private Hearing Aid Pathway", cat: "hearing", desc: "Assessment, hearing test coordination and a managed referral to private audiology with transparent pricing", priceMinor: 45000, durationLabel: "Multi-part", durationMin: 60 },
  { name: "Cataract Triage", cat: "hearing", desc: "Consultation on your visual symptoms, how cataracts are assessed, what surgery involves, and whether to seek referral now or wait", priceMinor: 7500, durationLabel: "30 min", durationMin: 30 },
  { name: "Pre-Operative Eye Assessment Review", cat: "hearing", desc: "For patients with a surgery date who want their assessment, risks and aftercare explained by an independent clinician before they sign consent", priceMinor: 25000, durationLabel: "45 min", durationMin: 45 },
  { name: "Founding 500: Dementia Memory Assessment Voucher", cat: "founding", desc: "One of 500 prepaid vouchers at founding pricing, before full price applies. Lock the price now, redeem after launch on 30 September 2026, or gift it to someone you love. Full price £895.", priceMinor: 69500, durationLabel: "90 min, redeemable after launch", durationMin: 90 },
  { name: "Founding 500: Fertility Advice plus Hormone Panel Voucher", cat: "founding", desc: "One of 500 prepaid vouchers at founding pricing, before full price applies. Lock the price now, redeem after launch on 30 September 2026, or gift it to someone you love. Full price £400.", priceMinor: 34500, durationLabel: "45 min plus sample kit, redeemable after launch", durationMin: 45 },
  { name: "Founding 500: Neurodivergent Assessment Voucher", cat: "founding", desc: "One of 500 prepaid vouchers at founding pricing, before full price applies. Lock the price now, redeem after launch on 30 September 2026, or gift it to someone you love. Full price £685.", priceMinor: 54500, durationLabel: "75 min, redeemable after launch", durationMin: 75 },
];

const BY_NAME = new Map(SERVICES.map((s) => [s.name, s]));

/// Catalogue entry for a service name, or null if it is not something we sell.
export function findService(name: unknown): Service | null {
  return BY_NAME.get(String(name ?? '').trim()) ?? null;
}

export function isVoucher(service: Service): boolean {
  return service.cat === FOUNDING_CAT;
}

/// Formats pence as GBP, e.g. 68500 -> "£685".
export function formatMinor(minor: number): string {
  return '£' + Math.round(minor / 100).toLocaleString('en-GB');
}
